.github/workflows/build-release.yml
build.sh
build/lin.sh
build/win.sh
linux-arm64v8/Dockerfile
linux-armv6/Dockerfile
linux-armv7/Dockerfile
linux-x64/Dockerfile
linuxmusl-x64/Dockerfile
win32-ia32/Dockerfile
win32-x64/Dockerfile

This will provide .tar.br files alongside the existing .tar.gz files for a given release. See #43 for more context.
@kleisauke Would net-vips benefit from these? We could also consider providing .tar.xz variants too.

Add Brotli-compressed release tarballs #43

---

THIRD-PARTY-NOTICES.md
build/lin.sh
build/patches/libspng-0.6-fixes.patch

In line with the Windows binaries. I've backported https://github.com/randy408/libspng/commit/b21b214b01ec6d52b8d733e473f1c6910db64d6f to help https://github.com/libvips/libvips/issues/1748.

Include libspng as dependency

---

build/lin.sh

The `--disable-deprecated` option was fixed in libvips 8.10.

Build binaries with --disable-deprecated

---

linux-x64/Dockerfile
linux-x64/Toolchain.cmake
linux-x64/meson.ini

By using `devtoolset-9` provided by RHEL/CentOS.

Build Linux x64 binaries with GCC 9.3.1

---

.github/workflows/build-release.yml
README.md
build.sh
build/win.sh
win32-arm64/Dockerfile
win32-arm64v8/Dockerfile

Version 8.10.2 of `build-win64-mxe` added support for Windows ARM32+ARM64: 
https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.2
This PR adds support for Windows ARM64 to `sharp-libvips`. Since Microsoft is focused on ARM64 only moving forward (AFAIK), I only added that version. I'm happy to add ARM32 as well if you think that will benefit the community. 😊

Add Windows arm64 support

---

build/lin.sh

The changes in 151cb8c3d892b9 broke the gdk-pixbuf build for me on darwin-x64. The command to delete the executables had no final semicolon, which causes an error using the `sed` binary installed on my Mac (it works fine with `gnu-sed`). Furthermore, the meson setup failed because of a missing variable [here](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/master/gdk-pixbuf/meson.build#L322) and the post-install script failed because it calls `gdk-pixbuf-query-loaders`, which we have not built.
Both these latter errors are in `if not meson.is_cross_build()` branches, which I don't seem to hit when running the linux-x64 build via docker, though I'm not entirely sure why that this is. If there is another reason for why the linux-x64 build does not fail, this PR might not be necessary at …

Fix gdk-pixbuf build on macOS

---

build/lin.sh

See: https://bugs.chromium.org/p/aomedia/issues/detail?id=2743#c5.
(I also added the `-DBUILD_SHARED_LIBS=FALSE` configure option to ensure that aom will always be built statically)

aom: switch to release tarball

---

build/lin.sh

Alpine Linux's patch seems to be compatible again with the latest GLib versions. I also switched to using the new Meson configure option for disabling the tests.

glib: use patch from Alpine Linux

---

build/lin.sh

The Alpine patch seems to apply without problems, but further on it causes issues when configuring GLib, see for example:
https://github.com/kleisauke/libvips-packaging/runs/1777505762
Sorry for not testing this properly in the first place.

Revert "glib: use patch from Alpine Linux (#80)"

---

build.sh
build/lin.sh
linux-arm64v8/Dockerfile
linux-armv6/Dockerfile
linux-armv7/Dockerfile
linux-x64/Dockerfile
linuxmusl-x64/Dockerfile

This PR allows the size vs perf optimisation level to be set per dependency.
There's no change (`-O3`) for vips, gif, orc, webp, spng, png16, jpeg, heif, lcms2, zlib, aom; everything else is optimised for size (`-Os`). This accounts for 7-9% reduction in binary size.
For Linux, it adds flags that allows the linker to remove unused sections (unsupported by cairo). This accounts for 1% reduction in binary size.
For Linux x64, it sets a minimum CPU requirement of Westmere (circa 2010) or later. This allows gcc to use CLMUL intrinsics, which helps improve zlib (de)compression performance (whilst we wait for zlib-ng).
@kleisauke Is there anything you think could be added/improved? Perhaps this approach might be something to consider for the Windows builds too?

Reduce size of binaries by up to 10%

---

THIRD-PARTY-NOTICES.md
build/lin.sh

libvips resets to libjpeg-turbo's `JCP_FASTEST` defaults so this can be considered a "no-op" unless mozjpeg features are explicitly set.
https://github.com/libvips/libvips/blob/dd57463c9a7f80730d70c4ff080bbd3f5ab1cc80/libvips/foreign/vips2jpeg.c#L594-L600
@kleisauke Would you like me to submit a PR to make this change as the default to https://github.com/libvips/build-win64-mxe/ also?

Switch from libjpeg-turbo to mozjpeg

---

build/lin.sh

Rather than exclude some modules that are not required, this approach excludes all optional modules then includes only what is needed.
This reduces the binary size by ~0.3MB.
When https://gitlab.gnome.org/GNOME/libxml2/-/commit/106757e8c1e26ad9b8c924c7f304074b79e082c5 is released we can also remove the `--with-regexps` flag.
@kleisauke We might want to use this approach for the Windows builds too.

Build a more minimal libxml2

---

THIRD-PARTY-NOTICES.md
build/lin.sh

Although I've done a fair amount of testing with it locally, this should probably be considered _experimental_ and I'll be marking it as such in the sharp documentation.
Due to the use of C99 variable length arrays, MSVC is totally unsupported. If gcc >= 9 is found then OpenMP support is enabled (clang will require https://github.com/mesonbuild/meson/issues/7435).
More details at https://github.com/lovell/libimagequant

Add libimagequant v2.4.1 BSD-2-Clause

---

THIRD-PARTY-NOTICES.md
build/lin.sh

The only changes to zlib-ng since RC2 appear to relate to tests, docs and CI so I'm happy it will be very close to the (supported) release, which means it's worth making the switch now so we can get some testing in too.
Closes #25

Switch from zlib to zlib-ng (stable release candidate)

---

build/lin.sh

This change makes getting a backtrace slightly more difficult in some circumstances, or at least the output is less useful, but with a worthwhile reduction in binary size.
It makes very little difference with macOS/clang, presumably as it is able to optimise this away already, so this change is for Linux/gcc only. There is also minimal impact on cross-compiled ARM binaries, so perhaps we should exclude them too?
Before:
```
22742608 libvips-cpp.so.42.12.7
8166054 libvips-8.10.6-linux-x64.tar.br
9891496 libvips-8.10.6-linux-x64.tar.gz
```
After:
```
21145168 libvips-cpp.so.42.12.7
7767290 libvips-8.10.6-linux-x64.tar.br
9354659 libvips-8.10.6-linux-x64.tar.gz
```

Linux x64: remove async unwind tables, ~7% smaller binary size

---

build/lin.sh

We can safely remove the `--with-regexps` flag, now that libxml2 v2.9.12 has been released.

xml2: build without support for regular expressions

---

linux-x64/Dockerfile

Reduces final binary size by ~2% (from 20974256 to 20539888 bytes), which I guess may be due to the following change:
> `-finline-functions` is now enabled at `-O2` and was retuned for better code size versus runtime performance trade-offs
https://gcc.gnu.org/gcc-10/changes.html
I think this is a relatively safe upgrade, but doing so via a PR for comments, if any.

Linux x64: upgrade to gcc 10

---

build/lin.sh

These dependencies provide their own hand-written SIMD intrinsics and use runtime CPU detection, so compile time optimisations are much less relevant.
This might be of possible interest to @kleisauke as it reduces the binary size by ~6% without any noticeable performance drop, hence the PR.
Before:
```
6869110 libaom.a
1708024 liborc-0.4.a
20095232 libvips-cpp.so.42.13.0
1120142 libwebp.a
```
After:
```
6320086 libaom.a
1295216 liborc-0.4.a
18751936 libvips-cpp.so.42.13.0
779230 libwebp.a
```

Optimise for binary size: aom, orc, webp

---

build/lin.sh

The glib maintainers started deprecating the outdated, PCRE1-based GRegex about 6 years ago:
https://bugzilla.gnome.org/show_bug.cgi?id=755693
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1451
This means we can pre-emptively remove it as there is no dependence on it from any of the libraries we rely on.
The sharp unit tests pass using the output.
The resultant binaries are only about 150KB smaller, but it all helps.

glib: remove deprecated/unused GRegex via patch

---

build/lin.sh

(I've no idea why Anitya sees this as pre-release: https://release-monitoring.org/project/10024/)

Bump dep: glib

---

build/lin.sh

Typically 'stability' in this context refers to API/ABI changes, which can currently be ignored for glib due to the use of static linking.
The parameter is tested via a _contains_ rather than _equals_ check as e.g. there may be future possible concepts of 'stability' that we do care about.
As discussed in #111

Add optional parameter to version_latest check, initially to allow 'unstable'

---

build/lin.sh

This PR updates FreeType to 2.11.0 and switches the build to use Meson instead. While doing this, I removed all occurrences of `LDFLAGS=${LDFLAGS/\$/}` (which removes the first `\$` from `-Wl,-rpath='\$\$ORIGIN/'`), since that is redundant for static libraries.
The version of proxy-libintl has also updated to use the [tagged 0.2 version](https://github.com/frida/proxy-libintl/releases/tag/0.2).

Bump deps: freetype

---

.circleci/config.yml
.github/workflows/build-release.yml
build/lin.sh
linux-arm64v8/Dockerfile
linux-arm64v8/Toolchain.cmake
linux-arm64v8/meson.ini

Closes #114
- Uses Centos 7 with latest gcc 10 (currently v10.2.1) so the glibc minimum version will drop from 2.31 to 2.17
- Runs on CircleCI ARM64 environment - https://circleci.com/docs/2.0/arm-resources/
- Adds workaround for librsvg not yet supporting rust aarch64 nightly multi-target (should probably patch this upstream)
Example build log - https://circleci.com/api/v1.1/project/github/lovell/sharp-libvips/20/output/103/0?file=true
@kleisauke Is this something you might be able to take advantage of for the net-vips packaging too? This change will allow use of e.g. the new ARM-based Lambda environment in AWS.

linux-arm64v8: replace cross-compilation with native build

---

build/lin.sh
linux-arm64v8/Dockerfile
linuxmusl-arm64v8/Dockerfile

This feature flag is no longer necessary after PR rust-lang/compiler-builtins#444. 
The only downside I can think of is that the standard library is now built without `panic_immediate_abort`.

ARM64: build librsvg without the -Zbuild-std feature flag

---

.github/workflows/build-release.yml
build.sh
build/lin.sh
linuxmusl-arm64v8/Dockerfile
linuxmusl-x64/Dockerfile

Using the `GITHUB_TOKEN` secret didn't work, since that access token
is scoped to the repository running the workflow. So, retrieving tags
from other repositories might still exceed the rate limit of GitHub's
Rest API.

Use `git ls-remote` to fetch the latest tag

---

build/lin.sh

- Remove `CPATH` env in favor of `CPPFLAGS`.
- Remove redundant `LIBRARY_PATH` env.
- Remove redundant sed replacements and configure options.
- Enable Arm Neon support in libwebp, if available.
- Enable WebP support in libtiff (https://github.com/lovell/sharp/issues/3198).
Consolidated `linux-x64` build diff:
<details>
<summary>Details</summary>
```diff
--- a/various-improvements-linux-x64.out
+++ b/various-improvements-linux-x64.out
@@ -4059,10 +4059,7 @@ checking whether to build static libraries... yes
Configuring for a minimal library
So far so good!
Checking zlib
-checking zlib.h usability... yes
-checking zlib.h presence... yes
-checking for zlib.h... yes
-checking for gzread in -lz... yes
+checking for Z... yes
Checking lzma
Disabling lzma compression support
Checking headers
@@ …
```

Various improvements

---

build/lin.sh
linux-arm64v8/Dockerfile
linuxmusl-arm64v8/Dockerfile

The underlying issue (#109) should be fixed with compiler-builtins
v0.1.55, available in Rust 1.59.0.

arm64v8: prefer latest stable version of Rust

---

build/lin.sh

This should be fixed with compiler-builtins v0.1.69, available in
Rust 1.60.0.

linux-armv{7,6}: remove `--allow-multiple-definition` linker flag

---

build/lin.sh

This is a non-functional change except for the latest patch URL, as that has been replaced by commit https://github.com/kleisauke/libheif/commit/0d44224914946a00d293c08bbaf4553acc985802 (which is a combination of cherry-picked commits available upstream).

heif: update patch URLs

---

build/lin.sh

This patch needed to be updated after https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2734.
It seems that it is now only needed for macOS, so remove the `linuxmusl` condition.

glib: update patch

---

linux-arm64v8/Dockerfile
linux-x64/Dockerfile

Python 3.6 is EOL and Meson >= 0.62.0 requires Python 3.7 or newer. See:
https://mesonbuild.com/Release-notes-for-0-62-0.html#minimum-required-python-version-updated-to-37
Also, prefer to install Ninja via pip.

Upgrade Python in CentOS 7 containers

---

linux-x64/Dockerfile
linuxmusl-x64/Dockerfile

The use of `-march=x86-64-v2` requires gcc 11, so this uses the almost-equivalent `-march=nehalem` with gcc 9 on Alpine.
I checked the zlib-ng source code and it compiles and includes functions for all common x64 intrinsics and uses runtime-dispatch, so will still take advantage of PCMUL intrinsics on newer hardware.
There appears to be a small ~4Kb increase in binary size due to this change.
Before:
```
17104592 libvips-cpp.so.42.15.0
```
After:
```
17108688 libvips-cpp.so.42.15.0
```
Fixes #153

Linux x64: align with v2 standard microarchitecture

---

build.sh
win32/Dockerfile

This container is used only for post-processing Windows binaries,
so we can safely bump to Debian 11 (bullseye).
The Linux ARMv7-A and ARMv6 containers still require Debian 10
(buster) to avoid a glibc version bump in the resulting binaries.

win32: upgrade Docker container to Debian 11 (bullseye)

---

.github/workflows/build-release.yml

Skipping this version is now implicitly done since Meson 0.63.2
was released, which reverted the commit that caused this linker
failure.
See: https://github.com/mesonbuild/meson/commit/0e0dbf7e35f1e368090682bfd4818589d3c64d6e

macOS: remove version requirement for Meson

---

.github/workflows/build-release.yml

Since GitHub actions migrated the Python installation to a universal package, which no longer adds the pip3 site-packages to the `PATH`, see: https://github.com/actions/runner-images/issues/6496.

macOS: install Meson and Ninja via Homebrew

---

build/lin.sh

This patch, from Alpine Linux, is approximately equivalent to setting `G_SLICE=always-malloc` and goes further by removing all the unused code. This should help prevent segfaults/hangs on QEMU-based emulated/interpreted environments, amongst others.
(The default memory allocator included in Windows UCRT is, I think, still bad enough to warrant retaining glib's slice logic in the Windows binaries.)
Related:
https://github.com/lovell/sharp/issues/3082
https://github.com/lovell/sharp/issues/3448
https://gitlab.gnome.org/GNOME/glib/-/issues/1079
https://gitlab.com/qemu-project/qemu/-/issues/285

glib: remove slice allocator (via Alpine Linux patch)

---

build/lin.sh

- Build libheif with CMake, as preferred by upstream since v1.14.0.
- Ensure to always specify `CMAKE_BUILD_TYPE` for CMake projects.
- Prefer to specify `CMAKE_INSTALL_LIBDIR` as relative path.
---
If necessary, I could also backport commit https://github.com/strukturag/libheif/commit/ee1e5087d2cc289a161de44c013e27300224529b. 
Note that calling `heif_init()` should not be required by libvips, despite what is mentioned in the [release notes of v1.14.0](https://github.com/strukturag/libheif/releases/tag/v1.14.0) - see:
https://github.com/strukturag/libheif/blob/16385339069d4bd931efd797032039255c75dfc2/libheif/heif.h#L310-L311

Bump deps: heif, pango

---

.github/workflows/build-release.yml

This reverts commit 944fbd2d2cac8c1d4a5043c6b73af9ca27ea8d51 and avoids depending on Python from Homebrew. The mentioned GitHub actions runner issue in PR https://github.com/lovell/sharp-libvips/pull/163 is ~~probably~~ a duplicate of https://github.com/actions/runner-images/issues/6507, which was fixed with commit https://github.com/actions/runner-images/commit/f6632ff53b24db9705c5b15bf90dbf05cc3fe295 ~~, but not yet deployed at the time of writing~~.
~~This PR is marked as a draft until GitHub updates its macOS runner images. After that, we can drop the workaround added in commit 27703f95ce1a68cb24b52fd590afeba45a2fe746.~~

Revert "macOS: install Meson and Ninja via Homebrew (#163)"

---

build/lin.sh

Requires at least Meson 0.64.0.
See https://mesonbuild.com/Installing.html#installation-tags.
Marked this PR as draft due to these TODO items:
No longer needed with Meson 0.64.0.
No longer needed with Meson 0.64.0.

Meson: install only a subset of the installable files

---

build/lin.sh

In line with commit kleisauke/wasm-vips@628f6fa and libvips/build-win64-mxe@3c04aa7.

tiff: avoid building unnecessary things

---

build/lin.sh

This will (hopefully temporarily) remove support for dzsave/tile operations.
The context for this is at https://gitlab.gnome.org/GNOME/libgsf/-/issues/28
Rather amusingly, it looks like librsvg was previously accessing libxml2 symbols via libgsf!
I'll sort a similar PR for the Windows binaries too.

gsf: remove due to use of incompatible LGPL-2.1-only

---

build/lin.sh

These remove a bit more glib code than I was expecting, overall resulting in a ~2% smaller binary.
Before:
```
-rw-r--r-- 1 root root  5646586 Mar 28 15:33 libgio-2.0.a
-rw-r--r-- 1 root root  2458480 Mar 28 15:32 libglib-2.0.a
-rw-r--r-- 1 root root    20398 Mar 28 15:32 libgmodule-2.0.a
-rw-r--r-- 1 root root   839672 Mar 28 15:32 libgobject-2.0.a
-rw-r--r-- 1 root root     2846 Mar 28 15:32 libgthread-2.0.a
...
-rwxr-xr-x 1 root root 16428664 Mar 28 15:44 libvips-cpp.so.42.16.2
```
After:
```
-rw-r--r-- 1 root root  4623762 Mar 28 16:12 libgio-2.0.a
-rw-r--r-- 1 root root  1910144 Mar 28 16:11 libglib-2.0.a
-rw-r--r-- 1 root root    17462 Mar 28 16:11 libgmodule-2.0.a
-rw-r--r-- 1 root root   615152 Mar 28 16:11 libgobject-2.0.a
-rw-r--r-- 1 root root     2358 Mar 28 16:11 …
```

glib: compile without macros (assert, checks)

---

build/lin.sh

In line with the Windows builds, where this isn't built by default.
https://github.com/libarchive/libarchive/blob/bd074c2531e867078788fe8539376c31119e4e55/configure.ac#L277-L280
Should fix the CI for the `linuxmusl-*` platforms.

archive: disable build of bsdunzip utility

---

build.sh
build/lin.sh
darwin-arm64v8/meson.ini
darwin-x64/meson.ini
linux-arm64v8/meson.ini
linux-armv6/meson.ini
linux-armv7/meson.ini
linux-x64/meson.ini
linuxmusl-arm64v8/meson.ini
linuxmusl-x64/meson.ini

Otherwise, it might inadvertently end up in the `lib64/` directory, resulting in the use of zlib 1.2.11 as provided by GLib as fallback.
<details>
<summary>Details</summary>
```
-- Installing: /target/lib64/libz.a
-- Installing: /target/include/zlib.h
-- Installing: /target/include/zlib_name_mangling.h
-- Installing: /target/include/zconf.h
-- Installing: /target/lib64/pkgconfig/zlib.pc
...
Run-time dependency zlib found: NO (tried pkgconfig, cmake and system)
Looking for a fallback subproject for the dependency zlib
Downloading zlib source from https://zlib.net/fossils/zlib-1.2.11.tar.gz
Downloading zlib patch from https://wrapdb.mesonbuild.com/v2/zlib_1.2.11-6/get_patch
Executing subproject zlib 
zlib| Project name: zlib
zlib| Project version: 1.2.11
zlib| C compiler for the host …
```

Ensure zlib-ng is installed in `lib/`

---

build/lin.sh

Size of resultant `libvips-cpp.42.dylib` file:
```
ARM64
before: 15915032
after:  15748120
x64
before: 18524800
after:  18326416
```
A small but not insignificant improvement. 
I tried various compiler flags to get the linker to remove more, e.g. `-gfull`, but to no avail.
(As an aside, there's still a big difference between x64 and ARM64, the bulk of which I think is coming from the libaom runtime detection logic.)

macOS: Remove unused functions at link time, ~1% smaller binaries

---

build/lin.sh

Before:
```
2023-10-19T15:02:51.0232087Z -- Installing: /target/lib64/pkgconfig/libhwy.pc
2023-10-19T15:09:01.8740127Z     SIMD support with highway         : NO
```
After:
```
2023-10-19T18:43:41.1109738Z -- Installing: /target/lib/pkgconfig/libhwy.pc
2023-10-19T18:49:16.1614328Z     SIMD support with highway         : YES
```
Apologies for not spotting this earlier.

hwy: ensure correct lib directory

---

THIRD-PARTY-NOTICES.md

The old URL was giving a 404 error.
Noticed while trying to integrate this file in wasm-vips.

Update libtiff licence location

---

.gitignore
README.md
npm/darwin-arm64/package.json
npm/darwin-x64/package.json
npm/dev/package.json
npm/linux-arm/package.json
npm/linux-arm64/package.json
npm/linux-s390x/package.json
npm/linux-x64/package.json
npm/linuxmusl-arm64/package.json
npm/linuxmusl-x64/package.json
npm/package.json
npm/populate.sh
npm/win32-ia32/package.json
npm/win32-x64/package.json

The packages these produced have all been tested with sharp - see https://github.com/lovell/sharp/actions/runs/6756293763
Once the use of these has settled I'd like to move to an approach where (signed) packages are published directly to npm during CI (rather than an intermediate GitHub release), but this can wait for a while - see https://github.com/lovell/sharp-libvips/issues/206

Add infrastructure to re-publish release tarballs as npm packages

---

.github/workflows/build-release.yml
.gitignore
README.md
build.sh
build/wasm.sh
npm/dev-wasm32/THIRD-PARTY-NOTICES.md
npm/dev-wasm32/package.json
npm/package.json
npm/populate.sh

This uses the wasm-vips scripts and containers to compile libvips and its dependencies as wasm32 static libraries.
Known limitations:
* Runs in CI but doesn't publish anywhere yet (see #206)
* Expects upstream libvips version to match the currently expected version for this repo, fails-fast otherwise

Add infrastructure to build WebAssembly static libs via wasm-vips

---

.github/workflows/build-release.yml
build/lin.sh
build/wasm.sh
platforms/linux-arm64v8/Dockerfile
platforms/linux-armv6/Dockerfile
platforms/linux-armv7/Dockerfile
platforms/linux-s390x/Dockerfile
platforms/linux-x64/Dockerfile
platforms/linuxmusl-arm64v8/Dockerfile
platforms/linuxmusl-x64/Dockerfile

GLib 2.79.0 requires the `packaging` Python module, so add this dependency to the Docker images as well.
> ```md
>  * Bump Meson dependency to 1.2.0 and depend on Python `packaging` module
> ```
> _From: https://gitlab.gnome.org/GNOME/glib/-/blob/2.79.0/NEWS#L25_
While we're here, fetch the latest wasm-vips commit by default using the special `HEAD` reference. On Github, this will be the tip of the default branch.

Bump deps: fontconfig, glib

---

platforms/linux-arm64v8/meson.ini
platforms/linux-armv6/meson.ini
platforms/linux-armv7/meson.ini
platforms/linux-s390x/meson.ini
platforms/linux-x64/meson.ini
platforms/linuxmusl-arm64v8/meson.ini
platforms/linuxmusl-x64/meson.ini

See:
https://mesonbuild.com/Release-notes-for-1-3-0.html#machine-files-pkgconfig-field-deprecated-and-replaced-by-pkgconfig
This should fix this deprecation warning:
```
DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config"
```

Meson: replace deprecated "pkgconfig" entry in machine files

---

.circleci/config.yml

See:
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
https://circleci.com/docs/using-arm/#ubuntu-2004---focal

CI: upgrade ARM64 runner and github-cli orb

---

build/lin.sh

It seems colored emoji glyphs are stored as PNG images in OpenType fonts, so compile FreeType with `-Dpng=enabled` to ensure that emoji can be rendered.
Tested by replacing `node_modules/@img/sharp-libvips-linux-x64/lib/libvips-cpp.so.42` with the produced binary and by doing:
```console
$ node -e "require('sharp')({text: { text: 'sharp is awesome! 🧩 ❤️', rgba: true }}).toFile('x.png')"
```
Context: https://github.com/lovell/sharp/issues/3959.

Build FreeType against libpng

---

build/lin.sh
platforms/darwin-arm64v8/meson.ini
platforms/darwin-x64/meson.ini
platforms/linux-arm64v8/meson.ini
platforms/linux-armv6/meson.ini
platforms/linux-armv7/meson.ini
platforms/linux-s390x/meson.ini
platforms/linux-x64/meson.ini
platforms/linuxmusl-arm64v8/meson.ini
platforms/linuxmusl-x64/meson.ini

Noticed this while doing:
```console
$ mkdir linux-x64
$ curl -fsSL https://github.com/lovell/sharp-libvips/releases/download/v8.15.2/libvips-8.15.2-linux-x64.tar.gz | tar xzC linux-x64
$ strings linux-x64/lib/libvips-cpp.so.42 | grep "/fontconfig"
<dir prefix="xdg">fonts</dir>  <cachedir>/target/var/cache/fontconfig</cachedir>  <cachedir prefix="xdg">fontconfig</cachedir>  <include ignore_missing="yes">/etc/fonts/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/fonts.conf</include></fontconfig>
/target/share/fontconfig/conf.avail
/target/var/cache/fontconfig
/fontconfig
```
With this PR, I see:
```console
$ strings libvips-8.15.2-linux-x64/lib/libvips-cpp.so.42 | grep "/fontconfig"
<dir …
```

Meson: uses system directories in machine files

---

build/lin.sh

(librsvg remains to be pinned to the stable 2.57.x series)

Bump deps: harfbuzz, pango, rsvg

---

build/lin.sh

To mirror the same patch added in https://github.com/libvips/build-win64-mxe/pull/61.

vips: disable HBR support in heifsave

---

build/lin.sh

Before:
```
-rw-r--r-- 1 root root   878202 Jul  8 09:21 libxml2.a
```
After
```
-rw-r--r-- 1 root root   554918 Jul  8 11:34 libxml2.a
```
Marked as draft as I didn't test this at runtime yet. I suspect the reader, writer, valid, http and zlib features of libxml2 were required by libgsf instead of librsvg.

xml2: switch from autotools to meson

---

build/lin.sh

This should help improve support for multiple versions of sharp that use differing versions of libvips running within the same process by ensuring `dlopen` accesses the relevant shared library.
Before:
```
lrwxrwxrwx 1 root root       17 Oct  8 15:05 libvips-cpp.so -> libvips-cpp.so.42
lrwxrwxrwx 1 root root       22 Oct  8 15:05 libvips-cpp.so.42 -> libvips-cpp.so.42.17.5
-rwxr-xr-x 1 root root 16313040 Oct  8 15:05 libvips-cpp.so.42.17.5
```
```
-rwxr-xr-x   1 runner  staff  18178880 Oct  8 15:13 libvips-cpp.42.dylib
lrwxr-xr-x   1 runner  staff        20 Oct  8 15:13 libvips-cpp.dylib -> libvips-cpp.42.dylib
```
After:
```
lrwxrwxrwx 1 root root       21 Oct  8 18:18 libvips-cpp.so -> libvips-cpp.so.8.15.5
-rwxr-xr-x 1 root root 16313040 Oct  8 18:18 libvips-cpp.so.8.15.5
```
``` …
```

Add libvips version number to shared library SONAME and filename

---

build/lin.sh

Issue https://gitlab.freedesktop.org/pixman/pixman/-/issues/69 was resolved via https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/71.

pixman: ARM64 intrinsics supported on Mach-O

---

platforms/linux-armv6/meson.ini
platforms/linux-ppc64le/meson.ini
platforms/linux-s390x/meson.ini
platforms/linuxmusl-arm64v8/meson.ini
platforms/linuxmusl-x64/meson.ini

C99 `printf()` semantics are well-supported by these Linux cross-targets, avoids the need for gnulib compat functions.
An alternative is setting up QEMU when cross-compiling, as this functionality is gated by `meson.can_run_host_binaries()`, but this is a bit simpler.
Note: this is not needed for macOS due to:
https://github.com/GNOME/glib/blob/2.83.3/meson.build#L1204-L1212
(you can verify this by checking for the `GLIB_USING_SYSTEM_PRINTF` definition in `lib/glib-2.0/include/glibconfig.h`)
Windows binaries, where this was originally found, will be fixed via PR https://github.com/libvips/build-win64-mxe/pull/72 or work-in-progress commit https://github.com/libvips/build-win64-mxe/commit/ea91b64f9a56369b2abf2d2f224f91f2420f8337.

Linux: ensure GLib's `g_print*()` functions wrap the system ones

---

build/lin.sh

Helps https://github.com/lovell/sharp/issues/1996; however, according to https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/1072, `dominant-baseline="middle"` may not be entirely accurate.

Bump dep: rsvg

---

build/posix.sh
platforms/linux-arm64v8/Dockerfile
platforms/linux-armv6/Dockerfile
platforms/linux-ppc64le/Dockerfile
platforms/linux-riscv64/Dockerfile
platforms/linux-s390x/Dockerfile
platforms/linuxmusl-arm64v8/Dockerfile
platforms/linuxmusl-x64/Dockerfile

Allows use of not-yet-stable flags, reduces binary size by ~200KB
- https://doc.rust-lang.org/beta/unstable-book/compiler-flags/fmt-debug.html
- https://doc.rust-lang.org/beta/unstable-book/compiler-flags/location-detail.html
Note that rust nightly does not appear to work with gcc10 on x64 (as used by the linux-x64 platform).
/cc @kleisauke who might be interested as it's something we'd investigated previously but was not available in rust nightly at that time.
```
-rw-r--r-- 1 root root 76483258 Jul  2 14:18 librsvg-2.a
-rwxr-xr-x 1 root root 13877204 Jul  2 14:19 libvips-cpp.so.8.17.0
```
```
-rw-r--r-- 1 root root 75580254 Jul  2 19:52 librsvg-2.a
-rwxr-xr-x 1 root root 13680556 Jul  2 19:53 libvips-cpp.so.8.17.0
```
```
-rw-r--r-- 1 root root 106437850 Jul  2 14:14 librsvg-2.a …
```

Use rust nightly on platforms where linker supports it

---

platforms/linux-arm64v8/Dockerfile
platforms/linux-x64/Dockerfile

Also, forcefully disable gold as the linker, as Rust still seems to emit a warning:
https://github.com/lovell/sharp-libvips/actions/runs/16145634431/job/45563658436#step:4:13810
(though, I think it's safe in that case, since we are building librsvg statically)
Note that we could use `export CARGO_PROFILE_RELEASE_TRIM_PATHS="all"` as a possible follow-up. However, enabling it isn't very straightforward, since `-Ztrim-paths` cannot be added to the `RUSTFLAGS` env variable, see:
https://doc.rust-lang.org/cargo/reference/unstable.html#profile-trim-paths-option

linux-x64: use rust nightly
